<?php

namespace App\Services\Ocr;

use Illuminate\Support\Facades\Log;
use Smalot\PdfParser\Parser as SmalotParser;
use Symfony\Component\Process\Process;

/**
 * Turns a PDF receipt into something Tesseract (or our parser) can use.
 *
 * Strategy:
 *   1. Try to extract embedded text via Smalot/PdfParser. If the PDF was
 *      generated by a POS / accounting app, it almost always contains real
 *      selectable text — using that is faster AND more accurate than OCR.
 *   2. If text extraction yields too little (typical of scanned PDFs that are
 *      really just bitmap images wrapped in PDF), render page 1 as a PNG
 *      via `pdftoppm` (Poppler) and let the caller OCR the image.
 *
 * Multi-page PDFs are out of scope for v1 — we always work off page 1, which
 * covers >99% of single-page receipts. A multi-page invoice support pass
 * would render every page and concatenate, which we'll add later if needed.
 */
class PdfPreprocessor
{
    /**
     * If extracted text has fewer printable characters than this, we treat
     * the PDF as image-based and fall back to rendering + OCR.
     */
    private const MIN_TEXT_CHARS = 50;

    /**
     * Resolution used when rendering PDFs to PNG for OCR. 300 DPI gives
     * Tesseract plenty of detail without producing absurd file sizes.
     */
    private const RENDER_DPI = 300;

    public function __construct(
        private SmalotParser $parser,
    ) {}

    /**
     * @return array{
     *     mode: 'text'|'image',
     *     text: ?string,
     *     image_path: ?string,   // absolute path to a temp PNG when mode=image
     *     cleanup: ?callable,    // call this to delete any temp files we created
     *     error: ?string,
     * }
     */
    public function preprocess(string $pdfAbsolutePath): array
    {
        if (! file_exists($pdfAbsolutePath)) {
            return $this->fail('PDF file not found at '.$pdfAbsolutePath);
        }

        // 1. Try direct text extraction first.
        try {
            $document = $this->parser->parseFile($pdfAbsolutePath);
            $text = trim($document->getText());

            if (mb_strlen($text) >= self::MIN_TEXT_CHARS) {
                return [
                    'mode' => 'text',
                    'text' => $text,
                    'image_path' => null,
                    'cleanup' => null,
                    'error' => null,
                ];
            }
        } catch (\Throwable $e) {
            // Bad PDF / encrypted / etc. — keep going to image fallback below.
            Log::info('[OCR/PdfPreprocessor] Text extraction failed, will try OCR', [
                'error' => $e->getMessage(),
            ]);
        }

        // 2. Fall back to rendering page 1 as PNG via pdftoppm.
        return $this->renderToImage($pdfAbsolutePath);
    }

    /**
     * Convert page 1 to a PNG using `pdftoppm`. Requires the `poppler-utils`
     * package on the host (handled by Dockerfile + `brew install poppler`).
     */
    private function renderToImage(string $pdfAbsolutePath): array
    {
        $binary = $this->resolvePdftoppmBinary();
        if (! $binary) {
            return $this->fail(
                'pdftoppm not found on PATH. Install poppler-utils on the server '
                .'(production: handled by the Dockerfile; local dev: `brew install poppler`).',
            );
        }

        $outputPrefix = sys_get_temp_dir().'/pdf-ocr-'.bin2hex(random_bytes(8));

        try {
            // -f 1 -l 1 → only first page; -png → output PNG; -r → DPI
            $process = new Process([
                $binary,
                '-png',
                '-r', (string) self::RENDER_DPI,
                '-f', '1',
                '-l', '1',
                $pdfAbsolutePath,
                $outputPrefix,
            ]);
            $process->setTimeout(30);
            $process->run();

            if (! $process->isSuccessful()) {
                return $this->fail(
                    'pdftoppm failed to render the PDF: '
                    .trim($process->getErrorOutput() ?: $process->getOutput()),
                );
            }
        } catch (\Throwable $e) {
            return $this->fail('Failed to invoke pdftoppm: '.$e->getMessage());
        }

        // pdftoppm appends "-1.png" (or "-01.png" depending on version) to the prefix.
        $candidates = glob($outputPrefix.'-*.png') ?: [];
        $imagePath = $candidates[0] ?? null;
        if (! $imagePath || ! file_exists($imagePath)) {
            return $this->fail('pdftoppm completed but no PNG was produced.');
        }

        return [
            'mode' => 'image',
            'text' => null,
            'image_path' => $imagePath,
            'cleanup' => function () use ($candidates) {
                foreach ($candidates as $f) {
                    @unlink($f);
                }
            },
            'error' => null,
        ];
    }

    /**
     * Locate the `pdftoppm` binary across common install paths
     * (PATH, Homebrew on Apple Silicon, Homebrew on Intel, /usr/bin, /usr/local/bin).
     */
    private function resolvePdftoppmBinary(): ?string
    {
        // 1. Honour PATH first.
        $which = trim((string) shell_exec('command -v pdftoppm 2>/dev/null'));
        if ($which !== '' && is_executable($which)) {
            return $which;
        }

        // 2. Common known locations.
        foreach (['/opt/homebrew/bin/pdftoppm', '/usr/local/bin/pdftoppm', '/usr/bin/pdftoppm'] as $candidate) {
            if (is_executable($candidate)) {
                return $candidate;
            }
        }
        return null;
    }

    private function fail(string $message): array
    {
        return [
            'mode' => 'image',
            'text' => null,
            'image_path' => null,
            'cleanup' => null,
            'error' => $message,
        ];
    }
}
